version: '3.8'
services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: unless-stopped
    ports:
      - "26000:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=cqrs
      - MONGO_DB_USERNAME=user
      - MONGO_DB_PASSWORD=user
    volumes:
      - ./docker-compose-volumes/db/mongo/data:/data/db/
      - ./docker-compose-volumes/log/mongo/logs:/var/log/mongodb/
      - ./docker-compose-volumes/initdb.d:/docker-entrypoint-initdb.d/

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker-compose-volumes/db/es/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq3'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./docker-compose-volumes/rabbitmq/data/:/var/lib/rabbitmq/
      - ./docker-compose-volumes/rabbitmq/log/:/var/log/rabbitmq

